### ISSUE TITLE
Works on Raspberry Pi with HP Scanjet 2400c :)

### ISSUE THREAD

**Issue by GaryA** [abusenius/insaned#1]
Hey Alex
I didn't know how to just leave you a nice comment so I had to create an issue.
I also fought with scanbd for 2 days before giving up and finding your project. Once I had found the latest sane backends and gcc compiler it was really easy to build, install and get working.
If you want to open the wiki I could add an article about installing on RPi for you.

The one thing I'm really missing at the moment is the ability to use the scanner via the buttons and via a networked PC. I can do one or the other but not both at the same time. phpSANE gives me a nice web interface from any PC but it cannot work if insaned is using libsane. If you could fix this the program would be perfect!

Best wishes from England
Gary

**Comment by abusenius** [comment]
Closed due to inactivity
