### ISSUE TITLE
insane on FreeBSD

### ISSUE THREAD

**Issue by displaced** [abusenius/insaned#8]
Hi,

Apologies for spamming-up your issue list, but just wanted to thank you for insaned!

I'm running FreeBSD and have just bought a Fujitsu ScanSnap S1500.  I've been struggling with scanbuttond and scanbd.  My experiences mirror yours: scanbuttond didn't see the scanner and scanbd was a royal pain to set up.  Even once I'd got it running, it would freeze whenever I shut the lid on the scanner (which turns it off).  

I've still got to set up my event scripts, but here's what I've got so far with insaned on FreeBSD 11.1:

I cloned the insaned repository and optimistically ran `make`.  No dice - FreeBSD keeps its non-base libs and headers under /usr/local/lib and /usr/local/include.  

I edited the Makefile to set CXXFLAGS and LDFLAGS as appropriate and used the more GNU-y `gmake` instead of just `make`.  Success!

I then ran `insaned` and it immediately saw my scanner and reported button events.  Upon closing the lid (and thus disconnecting the scanner), insaned spewed a stream of errors about not being able to access the device.

So, to solve that, I'm using FreeBSD's hardware manager, `devd` to launch insaned when the scanner connects and to kill `insaned` when it disconnects.

Just in case it'll help anyone else, here's my `/usr/local/etc/devd/insaned.conf` file:

```
notify 1 {
	match "subsystem" "DEVICE";
	match "type" "ATTACH";
	match "cdev" "ugen[0-9]+.[0-9]+";

	match "vendor" "0x04c5";
	match "product" "0x11a2";

 	action "chown -L cups:saned /dev/$cdev && chmod -L 660 /dev/$cdev";
	action "/usr/local/bin/insaned -e /usr/local/etc/insaned/";
};


notify 1 {
        match "subsystem" "DEVICE";
        match "type" "DETACH";

        match "vendor" "0x04c5";
        match "product" "0x11a2";

        action "/usr/bin/killall -9 insaned";
};
```

The vendor/product IDs will need to be adjusted for other makes and models of scanner. Also, the `chown` line may need the user/group names changing for other people's systems.  This line adjusts the permissions on the newly-created device file to allow non-root users to access the scanner.

Thanks again, and I hope this helps some others!

**Comment by abusenius** [comment]
Hi,

Thanks for testing insaned on FreeBSD, I'm glad it works for you :)

I have updated README and added your devd configuration file, so that others can find it more easily. I have also added /usr/local pathes to Makefile, since they don't seem to hurt, but I don't have FreeBSD to test it. A better solution would be to switch to CMake, I hope I can get to it at some time...

Feel free to comment if you see any other FreeBSD issues.
