### ISSUE TITLE
Service won't autostart on Ubuntu 16.04

### ISSUE THREAD

**Issue by MikeX7** [abusenius/insaned#9]
Hello,

I installed the .deb package on Ubuntu 16.04 64b and then rebooted the PC, but the insaned won't autostart. I looked into systemmd at insaned.serivce file, and an entry for it has been created there, so I am not sure why it isn't autostarting.

If I start the service manually as "sudo /usr/bin/insaned" then it works fine.

**Comment by abusenius** [comment]
Try this to enable autostart after reboot:
`sudo systemctl enable insaned` and then `sudo systemctl start insaned`

In any case I agree that it makes sense to automatically add the service to the autostart at installation because that is expected behavior. I will update the package file.

**Comment by MikeX7** [comment]
I see. As I am not too used to Linux, I had no idea you have to enable the service to autostart manually. I definitely think that pretty much everyone will assume, just like me, that it will get enabled during install and making it behave that way is a good idea. You should add a mention of this to the manual page of this project, to avoid any confusion.

Otherwise, great job on this package, it does its job and works exactly the way I want it to. I was about to give up on using my scanner buttons on Linux and then I found this great project.
